using Microsoft.CodeAnalysis;

namespace DependinatorCore.Parsing.Sources.Roslyn;

static class TypeParser
{
    public static IEnumerable<Item> ParseType(INamedTypeSymbol type, Compilation compilation, string moduleName)
    {
        var fullTypeName = Names.GetFullTypeName(type, moduleName);
        if (fullTypeName.EndsWith("AutoGeneratedProgram"))
            yield break;

        var fileSpan = Locations.GetFirstFileSpanOrNoValue(type);
        var leadingComment = CommentExtractor.GetLeadingCommentOrNoValue(type, fileSpan);
        var isPrivate = SymbolUtils.GetIsPrivate(type);

        yield return new Item(
            new Node(
                fullTypeName,
                new NodeProperties
                {
                    Type = NodeType.Type,
                    Description = leadingComment,
                    FileSpan = fileSpan,
                    IsPrivate = isPrivate,
                }
            ),
            null
        );

        foreach (var item in ParseTypeLinks(type, fullTypeName))
            yield return item;

        foreach (var item in ParseTypeMembers(type, fullTypeName, compilation))
            yield return item;
    }

    internal static IEnumerable<Item> ParseTypeLinks(INamedTypeSymbol type, string fullTypeName)
    {
        if (type.BaseType is { } baseType && baseType.SpecialType != SpecialType.System_Object)
            yield return LinkParser.Parse(baseType, fullTypeName);

        foreach (var interfaceType in type.Interfaces)
            yield return LinkParser.Parse(interfaceType, fullTypeName);
    }

    internal static IEnumerable<Item> ParseTypeMembers(
        INamedTypeSymbol type,
        string fullTypeName,
        Compilation compilation
    )
    {
        foreach (ISymbol member in GetMemberSymbols(type))
        {
            if (!SymbolEqualityComparer.Default.Equals(member.ContainingType, type))
                yield break;
            if (member is INamedTypeSymbol)
                yield break; // Nested type, handled by GetAllNamedTypes in SourceParser

            foreach (var item in MemberParser.ParseTypeMember(member, fullTypeName, compilation))
                yield return item;
        }
    }

    internal static IEnumerable<ISymbol> GetMemberSymbols(INamedTypeSymbol type)
    {
        return type.GetMembers().Where(m => !m.IsImplicitlyDeclared);
    }
}
