using Microsoft.CodeAnalysis;

namespace Dependinator.Roslyn.Parsing;

class IgnoredTypes
{
    public static bool IsIgnoredSystemType(INamedTypeSymbol symbol, string? typeName = null)
    {
        typeName ??= symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (
            typeName.StartsWith("global::Microsoft.")
            || typeName.StartsWith("global::__Blazor.")
            || typeName.EndsWith("AutoGeneratedProgram")
        )
            return true;

        var moduleName = symbol.ContainingModule?.Name;
        if (moduleName is null)
            return false;

        if (IsSystemIgnoredModuleName(moduleName))
            return true;

        return false;
    }

    public static bool IsSystemIgnoredModuleName(string moduleName)
    {
        return moduleName == "mscorlib"
            || moduleName == "PresentationFramework"
            || moduleName == "PresentationCore"
            || moduleName == "WindowsBase"
            || moduleName == "System"
            || moduleName.StartsWith("Microsoft.")
            || moduleName.StartsWith("System.");
    }
}
