#!/bin/bash
echo ""
echo "Update timezone to Europe/Stockholm"
sudo rm -rf /etc/localtime
sudo ln -s /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
date

echo ""
echo "Updating apt ..."
sudo apt update -q -y
echo ""
echo "Installing Python for WASM tooling ..."
sudo apt-get install -y python3 python-is-python3 1>/dev/null
echo ""
echo "Installing dotnet wasm-tools workload ..."
dotnet workload install wasm-tools
echo ""
echo "Installing mc for file browsning support ..."
sudo apt install -q mc -y 1>/dev/null
echo ""
echo "Installing lnav for log view support ..."
sudo apt install -q lnav -y 1>/dev/null
echo ""
echo "Installing xsel for copy selection ..."
sudo apt-get install -y xsel 1>/dev/null

echo ""
echo "setting working foler as safe in git confi ..."
git config --global --add safe.directory /workspaces/Dependinator

echo ""
echo "Adding dotnet tools to PATH ..."
if ! grep -qxF 'export PATH="$PATH:$HOME/.dotnet/tools"' ~/.profile; then
  echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> ~/.profile
fi

echo ""
echo "Installing gmd ..."
curl curl -sL https://raw.githubusercontent.com/michael-reichenauer/gmd/main/install.sh | bash

echo ""
echo "Please restart container to enable gmd"
echo "Done"
