#!/bin/bash
echo ""
echo "Update timezone to Europe/Stockholm"
sudo rm -rf /etc/localtime
sudo ln -s /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
date

echo ""
echo "Updating apt ..."
sudo apt update -q -y
echo ""
echo "Installing mc ..."
sudo apt install -q mc -y 1>/dev/null
echo ""
echo "Installing lnav ..."
sudo apt install -q lnav -y 1>/dev/null

echo ""
echo "Install gmd ..."
curl curl -sL https://raw.githubusercontent.com/michael-reichenauer/gmd/main/install.sh | bash

echo ""
echo "Install git post commit hook ..."
cp ./gmd/tools/post-commit-sample ./.git/hooks/post-commit
chmod +x ./.git/hooks/post-commit

echo ""
echo "Done"

