using Microsoft.CodeAnalysis;

namespace Dependinator.Roslyn.Parsing;

class IgnoredTypes
{
    public static bool IsIgnored(INamedTypeSymbol symbol, string? typeName = null)
    {
        typeName ??= symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (IsIgnoredType(typeName))
            return true;

        var moduleName = symbol.ContainingModule?.Name;
        if (moduleName is null)
            return false;

        if (IsIgnoredModuleName(moduleName))
            return true;

        return false;
    }

    static bool IsIgnoredType(string typeName)
    {
        return typeName.StartsWith("global::Microsoft.")
            || typeName.StartsWith("global::__Blazor.")
            || typeName.EndsWith("AutoGeneratedProgram")
            || typeName.EndsWith("_Imports");
    }

    static bool IsIgnoredModuleName(string moduleName)
    {
        return moduleName == "mscorlib"
            || moduleName == "PresentationFramework"
            || moduleName == "PresentationCore"
            || moduleName == "WindowsBase"
            || moduleName == "System"
            || moduleName.StartsWith("Microsoft.")
            || moduleName.StartsWith("System.");
    }
}
