using System.Reflection;
using System.Text.RegularExpressions;

// The built-in icon library: loads and caches node icons from embedded .svg resources for use
// in the diagram.
namespace Dependinator.UI.Diagrams.Icons;

// One icon read from an embedded .svg resource. Name equals the svg's `id` attribute and is the
// key used by `<use href="#name">` references; Group is the containing library folder (e.g. "Default");
// DisplayName is the user-facing name shown in icon lists (separators converted to spaces).
readonly record struct IconInfo(string Group, string Name, string DisplayName, string Svg);

// One selectable icon tint (see IconLibrary.IconColors); Swatch is the representative hex shown
// as the color dot in pickers.
readonly record struct IconColor(string Name, string Swatch);

// Loads and caches the built-in icon library from embedded `.svg` resources
// (src/Dependinator.UI/Diagrams/Icons/Library/<Group>/<Name>.svg).
//
// This is the single lookup seam for icons: every consumer goes through Get/Defs/All. A future
// user-provided icon source can be layered in here without touching any consumer.
static class IconLibrary
{
    const string Fallback = "Module";

    // Marker identifying the embedded icon resources, e.g.
    // "Dependinator.UI.Diagrams.Icons.Library.Default.Solution.svg".
    const string LibraryMarker = ".Library.";

    // All library icons are authored in one violet base palette around this hue; color variants
    // are generated by rotating each saturated color's hue by (target - base), so per-icon hue
    // nuance (gradients, slightly blue-leaning tones) is preserved in every variant.
    const double BaseHue = 252;

    // Colors below this saturation are neutral detail marks (white text bars, gray accents) and
    // are kept as-is when recoloring.
    const double NeutralSaturation = 0.05;

    // The Gray variant desaturates instead of re-hueing, matching the muted look of Private.svg.
    const double GraySaturationScale = 0.15;

    // The canonical violet used to derive each variant's swatch hex, so picker dots always match
    // the recolored icons (also the "Default" swatch).
    public const string DefaultSwatch = "#7B6BE8";

    // Selectable tints besides the default violet; a null hue means desaturate (Gray).
    static readonly (string Name, double? Hue)[] ColorDefinitions =
    [
        ("Blue", 215),
        ("Teal", 180),
        ("Green", 145),
        ("Amber", 40),
        ("Rose", 340),
        ("Gray", null),
    ];

    static readonly Lazy<Cache> cache = new(Load);

    // The selectable icon tints, for rendering color pickers (the default violet is represented
    // by a separate "Default" entry using DefaultSwatch, not listed here).
    public static readonly IReadOnlyList<IconColor> IconColors =
    [
        .. ColorDefinitions.Select(color => new IconColor(color.Name, RecolorHex(DefaultSwatch, color.Hue))),
    ];

    // The id of an icon's color variant in the library/defs, e.g. ("Type", "Blue") -> "Type--Blue".
    public static string VariantName(string name, string color) => $"{name}--{color}";

    public static string Get(string name)
    {
        var byName = cache.Value.ByName;
        if (byName.TryGetValue(name, out var svg))
            return svg;
        return byName.TryGetValue(Fallback, out var fallback) ? fallback : "";
    }

    // Whether an icon with the given name exists, so consumers can validate persisted icon
    // names and fall back to the node-type default for stale/unknown ones.
    public static bool Contains(string name) => cache.Value.ByName.ContainsKey(name);

    // All icon svgs concatenated, for rendering once into the diagram's <defs> so nodes can
    // reference them by id via <use href="#name">.
    public static string Defs => cache.Value.Defs;

    // The full library, for building grouped icon lists (e.g. a future icon picker).
    public static IReadOnlyList<IconInfo> All => cache.Value.All;

    static Cache Load()
    {
        var assembly = typeof(IconLibrary).Assembly;
        var icons = new List<IconInfo>();

        foreach (var resourceName in assembly.GetManifestResourceNames())
        {
            if (!resourceName.Contains(LibraryMarker) || !resourceName.EndsWith(".svg"))
                continue;

            if (TryParse(resourceName, ReadResource(assembly, resourceName), out var icon))
                icons.Add(icon);
        }

        // Generate the color variants of every icon. Variants resolve via Get/Contains and are
        // included in the defs so nodes can reference them, but are not part of All (icon
        // pickers list only the base icons; the tint is chosen separately).
        var byName = icons.ToDictionary(i => i.Name, i => i.Svg);
        var svgs = icons.Select(i => i.Svg).ToList();
        foreach (var icon in icons)
        {
            foreach (var (colorName, hue) in ColorDefinitions)
            {
                var variantSvg = Recolor(icon.Svg, colorName, hue);
                byName[VariantName(icon.Name, colorName)] = variantSvg;
                svgs.Add(variantSvg);
            }
        }

        var defs = string.Join("\n", svgs);
        return new Cache(byName, defs, icons);
    }

    // Recolors an icon svg into a tint variant: every id (the svg's own id plus per-icon gradient
    // ids) gets a "--<color>" suffix so the variant can coexist in the shared <defs>, and every
    // saturated hex color is re-hued (or desaturated for Gray) while neutral detail marks
    // (white/gray) are kept.
    static string Recolor(string svg, string colorName, double? hue)
    {
        svg = Regex.Replace(svg, "id=\"([^\"]+)\"", match => $"id=\"{match.Groups[1].Value}--{colorName}\"");
        svg = Regex.Replace(svg, @"url\(#([^)]+)\)", match => $"url(#{match.Groups[1].Value}--{colorName})");

        // Hex colors only occur as whole attribute values (fill="#8E6BFF", stop-color="#fff");
        // requiring the surrounding quotes avoids ever touching ids or other text.
        return Regex.Replace(
            svg,
            "(?<=\")#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})(?=\")",
            match => RecolorHex(match.Value, hue)
        );
    }

    // Re-hues one #RGB/#RRGGBB color (or desaturates it when hue is null), keeping saturation and
    // lightness; near-neutral colors (white/gray details) are returned unchanged.
    static string RecolorHex(string hex, double? hue)
    {
        var (r, g, b) = ParseHex(hex);
        var (h, s, l) = RgbToHsl(r, g, b);
        if (s < NeutralSaturation)
            return hex;

        (h, s) = hue is { } targetHue
            ? (((h + targetHue - BaseHue) % 360 + 360) % 360, s)
            : (h, s * GraySaturationScale);
        var (nr, ng, nb) = HslToRgb(h, s, l);
        return $"#{nr:X2}{ng:X2}{nb:X2}";
    }

    static (int R, int G, int B) ParseHex(string hex)
    {
        var value = hex[1..];
        if (value.Length == 3)
            value = $"{value[0]}{value[0]}{value[1]}{value[1]}{value[2]}{value[2]}";
        return (Convert.ToInt32(value[..2], 16), Convert.ToInt32(value[2..4], 16), Convert.ToInt32(value[4..6], 16));
    }

    static (double H, double S, double L) RgbToHsl(int red, int green, int blue)
    {
        var r = red / 255.0;
        var g = green / 255.0;
        var b = blue / 255.0;
        var max = Math.Max(r, Math.Max(g, b));
        var min = Math.Min(r, Math.Min(g, b));
        var l = (max + min) / 2;

        if (max == min)
            return (0, 0, l);

        var d = max - min;
        var s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        var h =
            max == r ? ((g - b) / d + (g < b ? 6 : 0)) * 60
            : max == g ? ((b - r) / d + 2) * 60
            : ((r - g) / d + 4) * 60;
        return (h, s, l);
    }

    static (int R, int G, int B) HslToRgb(double h, double s, double l)
    {
        if (s == 0)
        {
            var value = (int)Math.Round(l * 255);
            return (value, value, value);
        }

        var q = l < 0.5 ? l * (1 + s) : l + s - l * s;
        var p = 2 * l - q;
        return (Channel(p, q, h + 120), Channel(p, q, h), Channel(p, q, h - 120));
    }

    static int Channel(double p, double q, double hue)
    {
        hue = (hue % 360 + 360) % 360;
        var value =
            hue < 60 ? p + (q - p) * hue / 60
            : hue < 180 ? q
            : hue < 240 ? p + (q - p) * (240 - hue) / 60
            : p;
        return (int)Math.Round(value * 255);
    }

    static bool TryParse(string resourceName, string svg, out IconInfo icon)
    {
        // "...Library.Default.Solution.svg" -> group "Default", name "Solution".
        var relative = resourceName[(resourceName.IndexOf(LibraryMarker) + LibraryMarker.Length)..];
        relative = relative[..^".svg".Length];

        var split = relative.LastIndexOf('.');
        if (split <= 0)
        {
            icon = default;
            return false;
        }

        var group = relative[..split];
        var name = relative[(split + 1)..];
        icon = new IconInfo(group, name, ToDisplayName(name), svg);
        return true;
    }

    // Icon library file names can contain '-'/'_' separators (common in e.g. Azure/AWS icon
    // sets); the display name shown in icon lists uses spaces instead.
    internal static string ToDisplayName(string name) => name.Replace('-', ' ').Replace('_', ' ').Trim();

    static string ReadResource(Assembly assembly, string resourceName)
    {
        using var stream = assembly.GetManifestResourceStream(resourceName)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    sealed record Cache(IReadOnlyDictionary<string, string> ByName, string Defs, IReadOnlyList<IconInfo> All);
}
