using System.Reflection;
using System.Text.RegularExpressions;

// The built-in icon library: loads and caches node icons from embedded .svg resources for use
// in the diagram.
namespace Dependinator.UI.Diagrams.Icons;

// One icon read from an embedded .svg resource. Name equals the svg's `id` attribute and is the
// key used by `<use href="#name">` references; Group is the containing library folder (e.g. "Default");
// DisplayName is the user-facing name shown in icon lists (separators converted to spaces).
readonly record struct IconInfo(string Group, string Name, string DisplayName, string Svg);

// One selectable icon tint (see IconLibrary.IconColors); Swatch is the representative hex shown
// as the color dot in pickers.
readonly record struct IconColor(string Name, string Swatch);

// One icon library group (a Library subfolder) with its user-facing label, for rendering
// grouped icon pickers (e.g. the icon dialog's tabs).
readonly record struct IconGroup(string Name, string Label);

// Loads and caches the built-in icon library from embedded `.svg` resources
// (src/Dependinator.UI/Diagrams/Icons/Library/<Group>/<Name>.svg).
//
// This is the single lookup seam for icons: every consumer goes through Get/Defs/All. A future
// user-provided icon source can be layered in here without touching any consumer.
static class IconLibrary
{
    const string Fallback = "Module";

    // Marker identifying the embedded icon resources, e.g.
    // "Dependinator.UI.Diagrams.Icons.Library.Default.Solution.svg".
    const string LibraryMarker = ".Library.";

    // The library groups in display order: folder name, user-facing label, and whether tint
    // color variants are generated. The hand-authored groups share the violet base palette and
    // support tinting; the cloud brand icon sets (imported via ./scripts/import-icons) keep their
    // official colors, so tinting is skipped for them. Unknown groups sort last, untinted.
    static readonly (string Name, string Label, bool Tinted)[] GroupOrder =
    [
        ("Default", "Default", true),
        ("General", "General", true),
        ("Azure", "Azure", false),
        ("Aws", "AWS", false),
        ("Google", "Google", false),
    ];

    // All library icons are authored in one violet base palette around this hue; color variants
    // are generated by rotating each saturated color's hue by (target - base), so per-icon hue
    // nuance (gradients, slightly blue-leaning tones) is preserved in every variant.
    const double BaseHue = 252;

    // The canonical violet used to derive each variant's swatch hex, so picker dots always match
    // the recolored icons (also the "Default" swatch).
    public const string DefaultSwatch = "#7B6BE8";

    static readonly Lazy<Cache> cache = new(Load);

    // The selectable icon tints (the shared accent colors, see ColorUtil), for rendering color
    // pickers (the default violet is represented by a separate "Default" entry using
    // DefaultSwatch, not listed here).
    public static readonly IReadOnlyList<IconColor> IconColors =
    [
        .. ColorUtil.AccentColors.Select(color => new IconColor(
            color.Name,
            ColorUtil.ShiftHue(DefaultSwatch, BaseHue, color.Hue)
        )),
    ];

    // The id of an icon's color variant in the library/defs, e.g. ("Type", "Blue") -> "Type--Blue".
    public static string VariantName(string name, string color) => $"{name}--{color}";

    public static string Get(string name)
    {
        var byName = cache.Value.ByName;
        if (byName.TryGetValue(name, out var svg))
            return svg;
        return byName.TryGetValue(Fallback, out var fallback) ? fallback : "";
    }

    // Whether an icon with the given name exists, so consumers can validate persisted icon
    // names and fall back to the node-type default for stale/unknown ones.
    public static bool Contains(string name) => cache.Value.ByName.ContainsKey(name);

    // All icon svgs concatenated, for rendering once into the diagram's <defs> so nodes can
    // reference them by id via <use href="#name">.
    public static string Defs => cache.Value.Defs;

    // The full library in display order (grouped by GroupOrder), for building grouped icon
    // lists (e.g. the icon picker).
    public static IReadOnlyList<IconInfo> All => cache.Value.All;

    // The library groups that have icons, in display order, for rendering the picker's tabs.
    public static IReadOnlyList<IconGroup> Groups => cache.Value.Groups;

    // The user-facing label of a group (e.g. "Aws" -> "AWS").
    public static string GroupLabel(string group)
    {
        foreach (var (name, label, _) in GroupOrder)
        {
            if (name == group)
                return label;
        }
        return group;
    }

    internal static int GroupRank(string group)
    {
        for (int i = 0; i < GroupOrder.Length; i++)
        {
            if (GroupOrder[i].Name == group)
                return i;
        }
        return GroupOrder.Length;
    }

    static bool IsTinted(string group) => GroupOrder.Any(g => g.Name == group && g.Tinted);

    static Cache Load()
    {
        var assembly = typeof(IconLibrary).Assembly;
        var icons = new List<IconInfo>();

        foreach (var resourceName in assembly.GetManifestResourceNames())
        {
            if (!resourceName.Contains(LibraryMarker) || !resourceName.EndsWith(".svg"))
                continue;

            if (TryParse(resourceName, ReadResource(assembly, resourceName), out var icon))
                icons.Add(icon);
        }

        icons = icons
            .OrderBy(i => GroupRank(i.Group))
            .ThenBy(i => i.Group, StringComparer.Ordinal)
            .ThenBy(i => i.DisplayName, StringComparer.Ordinal)
            .ToList();

        // Generate the color variants of every tintable icon. Variants resolve via Get/Contains
        // and are included in the defs so nodes can reference them, but are not part of All
        // (icon pickers list only the base icons; the tint is chosen separately).
        var byName = icons.ToDictionary(i => i.Name, i => i.Svg);
        var svgs = icons.Select(i => i.Svg).ToList();
        foreach (var icon in icons.Where(i => IsTinted(i.Group)))
        {
            foreach (var (colorName, hue) in ColorUtil.AccentColors)
            {
                var variantSvg = Recolor(icon.Svg, colorName, hue);
                byName[VariantName(icon.Name, colorName)] = variantSvg;
                svgs.Add(variantSvg);
            }
        }

        var defs = string.Join("\n", svgs);
        var groups = icons.Select(i => i.Group).Distinct().Select(g => new IconGroup(g, GroupLabel(g))).ToList();
        return new Cache(byName, defs, icons, groups);
    }

    // Recolors an icon svg into a tint variant: every id (the svg's own id plus per-icon gradient
    // ids) gets a "--<color>" suffix so the variant can coexist in the shared <defs>, and every
    // saturated hex color is re-hued (or desaturated for Gray) while neutral detail marks
    // (white/gray) are kept.
    static string Recolor(string svg, string colorName, double? hue)
    {
        svg = Regex.Replace(svg, "id=\"([^\"]+)\"", match => $"id=\"{match.Groups[1].Value}--{colorName}\"");
        svg = Regex.Replace(svg, @"url\(#([^)]+)\)", match => $"url(#{match.Groups[1].Value}--{colorName})");

        // Hex colors only occur as whole attribute values (fill="#8E6BFF", stop-color="#fff");
        // requiring the surrounding quotes avoids ever touching ids or other text.
        return Regex.Replace(
            svg,
            "(?<=\")#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})(?=\")",
            match => ColorUtil.ShiftHue(match.Value, BaseHue, hue)
        );
    }

    static bool TryParse(string resourceName, string svg, out IconInfo icon)
    {
        // "...Library.Default.Solution.svg" -> group "Default", name "Solution".
        var relative = resourceName[(resourceName.IndexOf(LibraryMarker) + LibraryMarker.Length)..];
        relative = relative[..^".svg".Length];

        var split = relative.LastIndexOf('.');
        if (split <= 0)
        {
            icon = default;
            return false;
        }

        var group = relative[..split];
        var name = relative[(split + 1)..];
        icon = new IconInfo(group, name, ToDisplayName(name), svg);
        return true;
    }

    // Icon library file names can contain '-'/'_' separators (common in e.g. Azure/AWS icon
    // sets); the display name shown in icon lists uses spaces instead.
    internal static string ToDisplayName(string name) => name.Replace('-', ' ').Replace('_', ' ').Trim();

    static string ReadResource(Assembly assembly, string resourceName)
    {
        using var stream = assembly.GetManifestResourceStream(resourceName)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    sealed record Cache(
        IReadOnlyDictionary<string, string> ByName,
        string Defs,
        IReadOnlyList<IconInfo> All,
        IReadOnlyList<IconGroup> Groups
    );
}
