// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DependinatorVse
{
		static class Vsix
		{
				public const string Id = "0117fbb8-b3c3-4baf-858e-d7ed140c01f4";
				public const string Name = "Dependinator";
				public const string Description = @"Visualize program structure and dependencies in a map like view to make it easier to understand and refactor the architecture.";
				public const string Language = "en-US";
				public const string Version = "1.0";
				public const string Author = "Michael Reichenauer";
				public const string Tags = "Visualize, structure, architecture, code, refactor, dependencies";
		}
}
